name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm' # Active le cache npm pour accélérer l'installation

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17' # Version recommandée pour Android / React Native récent

    - name: Install dependencies
      run: npm install
    
    # Génère proprement le dossier /android et le Gradle Wrapper
    - name: Generate Android folder
      run: npx expo prebuild --platform android
    
    - name: Cache Gradle Packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make Gradle executable
      run: chmod +x android/gradlew

    - name: Build APK (Release)
      run: |
        cd android
        ./gradlew assembleRelease --no-daemon
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 30
        
